### ISSUE TITLE
Chatbase not showing dashboard data

### ISSUE THREAD

**Issue by JPThorne** [google/chatbase-dotnet#1]
Hi there, struggling to find some forum to get help on this. We've started using chatbase and are struggling to see our data in the dashboard. The API returns 200's with message_ids. Anyone able to point me in the right direction in terms of how to debug this further?

**Comment by cristiancavalli** [comment]
Hey @JPThorne! Currently our metrics are computed on a periodic basis (~6 hours). This is probably why you did not see your Chatbase dashboard immediately. We are rolling out an update which should shorten this turn-around in the very near-future and will include accompanying information in the documentation which describes the calculation timing. If you are getting 200's back though that means the API is getting your messages and your metrics should be available over the next 6 hour window. For posterity I won't close this issue until our next update system is rolled out and I will ping this thread with that update systems documentation.

**Comment by JPThorne** [comment]
Hi @cristiancavalli thanks for getting back to me. I am aware of the 6hr gap as mentioned in the FAQs.

However, in our case we have never seen any of our data come through to the dashboard, except in the session flow. There are no 'sessions', no 'active users', no 'messages' even. 

For example:
![image](https://user-images.githubusercontent.com/1411816/29505850-ef21a348-8648-11e7-938b-1b66beb0db65.png)

And:
![image](https://user-images.githubusercontent.com/1411816/29505925-57fc7352-8649-11e7-8bf5-8ad843c4c91b.png)

Etc. 

Will be good to see what an update brings, although at this point I feel there is an underlying issue with the data being processed. 

Should the API return 200's but not display our data for some reason?

**Comment by vmkrish** [comment]
Looking at the entities in the database, it seems like we're receiving the entities properly.  However, I noticed that some of them have a non-UTC timezone set in our backend (which I didn't think was possible through the normal http endpoint?).  @cristiancavalli Maybe this is an issue specific to this library?

Alternatively, right now we only support viewing metrics for data sent approximately realtime (with maybe up to ~15 minutes of delay).  If you're sending the data with historical timestamps, that could also explain the issue you are encountering.

**Comment by JPThorne** [comment]
@vmkrish thanks for the reply. I followed the docs here: https://chatbase.com/documentation/generic and posted a timestamp according to: 

"time_stamp:  int,    <required> milliseconds since the UNIX epoch, used to sequence messages" 

I think I am sending the data with current timestamps, as opposed to historical. I will re-investigate this and see if it helps. I only posted here as I had not yet received any responses from support channels anywhere else. 

Referring to your mail - live-analytics are good for us, although of course the chatbase console does seem to support 'historical' data up to a month ago?

**Comment by JPThorne** [comment]
Perhaps worth noting - on not seeing the data after a day, I tried several approaches for the timestamps, all of which did return HTTP 200's. 

- Initially I cast my current DateTime to an int. 
- Then tried a string
- Tried a long
- Ended up on a Int64.

**Comment by vmkrish** [comment]
@JPThorne Looking more closely, I was able to verify that you are setting the timestamps correctly.  So I suspect it's a bug with the library (and perhaps timezones?).  I will ask Cris to investigate tomorrow during US working hours.

**Comment by vmkrish** [comment]
Also, regarding the live vs historical analytics - historical data will be displayed, but we must have received the data at the time.  So for example, for the full 30-day graph to be populated, you would have to send data, live, for 30 days, as opposed to sending a batch of 30-days worth of data all at once.

**Comment by JPThorne** [comment]
Thanks @vmkrish looking forward to any possible feedback from @cristiancavalli. Yes, what you say re historical vs live makes sense.

**Comment by cristiancavalli** [comment]
@vmkrish @JPThorne Looking at the code again I don't think it's the time_stamp field -- just tested the timestamp code now on:
http://csharppad.com/gist/52bfd613f9e4dbfff71ad33c2a4289df

and it's generating valid integer data on that field which I then checked against:
https://www.epochconverter.com/

And it gave me the correct human-readable date back.

For reference here's the code:
https://github.com/google/chatbase-dotnet/blob/master/Chatbase/Message.cs#L62

Btw all timestamps are UTC from the client

**Comment by cristiancavalli** [comment]
@JPThorne thanks for working with us on this and apologies again for the issues with your data. The good news is that I am close to certain that we have identified the issue preventing your account from properly displaying data and you should start seeing data backfilled into your bots. Please tell me if you do not see at least some data having appeared in your account.

Thanks again,
Cris

**Comment by JPThorne** [comment]
Perfect, thank you for all the feedback. I am seeing all sorts of data now!

**Comment by SergeyLobanov** [comment]
Hi everyone, it looks like I have the same issue as @JPThorne. I use Facebook MessageAPI and also receive 200 response. The first request was sent yesterday, more than 6 hours ago, but I still don't see any data on my dashboard (only the "not_handled" flag was updated in Integration Completeness list). Could you help me with this, please? @cristiancavalli @vmkrish

**Comment by cristiancavalli** [comment]
Hey @SergeyLobanov sorry to hear that your data is not showing up at the moment -- please reach out to chatbase-feedback@google.com with your api-key and a quick description of your issue and we'll work on identifying the issue asap. Thanks!

**Comment by SergeyLobanov** [comment]
Thank you a lot @cristiancavalli, I have sent the email, waiting for an answer.

**Comment by Finocia** [comment]
Hai , am using the chatbase , i have used the code from this article:https://medium.com/google-developers/analytics-for-actions-d8212a6bf6a5, to integrate dialogflow chatbot with the chatbase ,but it is not showing me any analytics in the chatbase ,it is saying me that "Bot hasn't send  data yet" , i have even set the API key ,Please advise me how to get the analytics in the chatbase.

Thanks in advance...
